include $(UAL)/env/$(UAL_ARCH)/Makefile.config

INC      = -I$(UAL_ACCSIM)/src  -I$(UAL_PAC)/src  -I$(UAL_CORE)/include 
LIBS     = -L$(UAL_ACCSIM)/lib/$(UAL_ARCH) -L$(UAL_PAC)/lib/$(UAL_ARCH) -L$(UAL_CORE)/lib/$(UAL_ARCH) -lUal 

$(UAL_ACCSIM)/lib/$(UAL_ARCH)/obj/%.o : %.cc
	$(CC) $(CCFLAGS) $(INC) -c $< -o $@;
