
MAKE     = make
PERL     = perl

LEX      = flex
YACC     = bison
YACC_LIB = -lfl -lm

GPERF    = gperf

cc       = gcc -g
CC       = g++ -g                                 # Compiler
#CCFLAGS = -O -fpic -ansi -frepo -pedantic -Wall  # Compilation flags
CCFLAGS  = -O -fpic  -Wall  -Wno-deprecated       # Compilation flags

DLD      = g++                                    # Dynamic linker
DLDFLAGS = -shared                                # Dynamic linker flags
LD       = g++                                    # Linker
LDFLAGS  =                                        # Linker flags


AR       = ar
ARFLAGS  = cr
RANLIB   = ranlib

#USE_GPU  = FALSE
