include $(UAL)/env/$(UAL_ARCH)/Makefile.config

INC      = -I$(UAL_PAC)/src -I$(UAL_CORE)/include 
LIBS     = -L$(UAL_PAC)/lib/$(UAL_ARCH) -L$(UAL_CORE)/lib/$(UAL_ARCH) -lUal -ldl 

#ifdef XERCESCROOT
#  LIBS    += -L$(XERCESCROOT)/lib -lxerces-c         
#else
#endif

$(UAL_PAC)/lib/$(UAL_ARCH)/obj/%.o : %.cc
	$(CC) $(CCFLAGS) $(INC) -c $< -o $@;

$(UAL_PAC)/lib/$(UAL_ARCH)/obj/%.o : %.c
	$(cc) $(CCFLAGS) $(INC) -c $< -o $@;
