
MAKE     = gmake
PERL     = perl

LEX      = flex
YACC     = bison
YACC_LIB = -ll -ly -lm

GPERF    = gperf

cc	 = gcc
CC       = g++                                    # Compiler
#CCFLAGS = -O -fpic -ansi -frepo -pedantic -Wall  # Compilation flags
CCFLAGS  = -O -fpic -ansi  -Wall         # Compilation flags

DLD      = g++                                    # Dynamic linker
DLDFLAGS = -shared                                # Dynamic linker flags
LD       = g++                                    # Linker
LDFLAGS  =                                        # Linker flags


AR       = ar
ARFLAGS  = cr
RANLIB   = ranlib

