include $(SXF)/config/$(SXF_ARCH)/Makefile.config

compile : 
	cp $(CORE)/src/sxf/sxf.ll sxf.ll.txt
	cp $(CORE)/src/sxf/sxf.yy sxf.yy.txt
	cp $(CORE)/src/sxf/elements.gperf elements.gperf.txt		
clean:
	rm -rf *.txt 