include $(UAL)/env/$(UAL_ARCH)/Makefile.config

# QT

MOC        = $(QTDIR)/bin/moc
UIC        = $(QTDIR)/bin/uic

CCFLAGS  += -pipe -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT

QTINC     += -I$(QTDIR)/mkspecs/default -I$(QTDIR)/include
QTLIBS    += -Wl,-rpath,$(QTDIR)/lib -L$(QTDIR)/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 

# ROOT

ROOTCFLAGS    = $(shell root-config --cflags)
ROOTLIBS      = $(shell root-config --new)
ROOTGLIBS     = $(shell root-config --glibs) -lThread -lTable -lGQt -lQtGui 

CXXFLAGS     += -I$(QTROOTSYSDIR)/include -I$(ROOTSYS)/include # $(ROOTCFLAGS)


# UAL 

UALINC += -I$(UAL_GUI)/ROOT/src
UALINC += -I$(UAL_GUI)/QT/src

UALINC += -I$(UAL)/ext/UI/include
UALINC += -I$(UAL_AIM)/src
UALINC += -I$(UAL_TIBETAN)/src 
UALINC += -I$(UAL_SXF)/src 
UALINC += -I$(UAL_ACCSIM)/src 
UALINC += -I$(UAL_TEAPOT)/src 
UALINC += -I$(UAL_PAC)/src 
UALINC += -I$(UAL_CORE)/include
UALINC += -I$(UAL_ZLIB)/src
UALINC += -I$(UAL)/tools/include -I$(UAL)/tools/include/libxml2
UALINC += -I$(SXF)/src 

UALLIBS  = 
UALLIBS += -L$(UAL)/ext/UI/lib/$(UAL_ARCH)   -lUalUI
UALLIBS += -L$(UAL_AIM)/lib/$(UAL_ARCH)      -lAim
UALLIBS += -L$(UAL_TIBETAN)/lib/$(UAL_ARCH)  -lTibetan
UALLIBS += -L$(UAL_SXF)/lib/$(UAL_ARCH)      -lUalSXF2
UALLIBS += -L$(UAL_ACCSIM)/lib/$(UAL_ARCH)   -lAccsim
UALLIBS += -L$(UAL_TEAPOT)/lib/$(UAL_ARCH)   -lTeapot 
UALLIBS += -L$(UAL_PAC)/lib/$(UAL_ARCH)      -lPacSMF -lPacOptics -lPacSurvey -lPac
UALLIBS += -L$(UAL_ZLIB)/lib/$(UAL_ARCH)     -lZTps
UALLIBS += -L$(UAL_CORE)/lib/$(UAL_ARCH)     -lUal
UALLIBS += -L$(SXF)/lib/$(UAL_ARCH)          -lSXF
UALLIBS += -L$(UAL)/tools/$(UAL_ARCH)        -lpcre -lxml2

# Linux with gcc

CCFLAGS += $(QTINC) $(UALINC) $(INC) -I$(QTROOTSYSDIR)/include -I$(ROOTSYS)/include

LDFLAGS  += $(QTINC) $(UALINC) $(INC) -I$(ROOTSYS)/include
LDFLAGS  += $(ROOTLIBS) $(ROOTGLIBS) $(UALLIBS) $(QTLIBS) $(LIBS)

%.hh: %.ui 
	$(UIC) $< -o $@

moc_%.cc: %.hh
	$(MOC)  $< -o $@


$(UAL_GUI)/ROOT/lib/$(UAL_ARCH)/obj/%.o : %.cc
	$(CC) $(CCFLAGS) $(INC) -c $< -o $@;


