include $(UAL)/env/$(UAL_ARCH)/Makefile.config

INC +=  -I$(UAL_SIMBAD)/src \
	-I$(UAL_TEAPOT)/src \
	-I$(UAL_PAC)/src \
	-I$(UAL_ZLIB)/src \
	-I$(UAL_CORE)/include \
	-I$(UAL)/tools/include

LIBS += -L$(UAL_SIMBAD)/lib/$(UAL_ARCH) \
	-L$(UAL_TEAPOT)/lib/$(UAL_ARCH) \
	-L$(UAL_PAC)/lib/$(UAL_ARCH) \
	-L$(UAL_CORE)/lib/$(UAL_ARCH) \
	-lPac -lUal

$(UAL_SIMBAD)/lib/$(UAL_ARCH)/obj/%.o : %.cc
	$(CC) $(CCFLAGS) $(INC) -c $< -o $@;
