include $(UAL)/env/$(UAL_ARCH)/Makefile.config

INC +=  -I$(UAL_SPINK)/src \
	-I$(UAL_TEAPOT)/src \
	-I$(UAL_PAC)/src \
	-I$(UAL_ZLIB)/src \
	-I$(UAL_CORE)/include

LIBS += -L$(UAL_SPINK)/lib/$(UAL_ARCH) \
	-L$(UAL_TEAPOT)/lib/$(UAL_ARCH) \
	-L$(UAL_PAC)/lib/$(UAL_ARCH) \
	-L$(UAL_CORE)/lib/$(UAL_ARCH) \
	-lPac -lUal -lPacSMF -lTeapot -lPacOptics

$(UAL_SPINK)/lib/$(UAL_ARCH)/obj/%.o : %.cc
	$(CC) $(CCFLAGS) $(INC) -c $< -o $@;

ifeq ($(USE_GPU), TRUE)
 
NVCC	= nvcc  -arch=sm_13 
NVCCFLAGS  = --compiler-options '-O -fpic -g'
$(UAL_SPINK)/lib/$(UAL_ARCH)/obj/%.cu.o : %.cu
	$(NVCC) $(INC) -g --compiler-options '-fpic' -c $< -o $@;
endif

