include $(UAL)/env/$(UAL_ARCH)/Makefile.config


#NVCC = nvcc -m64 
INC +=  -I$(UAL_SPINK)/src/SPINK/Propagator \
	-I$(UAL_SPINK)/src \
	-I$(UAL_TEAPOT)/src \
	-I$(UAL_PAC)/src \
	-I$(UAL_ZLIB)/src \
	-I$(UAL_CORE)/include

LIBS += -L$(UAL_SPINK)/lib/$(UAL_ARCH) \
	-L$(UAL_TEAPOT)/lib/$(UAL_ARCH) \
	-L$(UAL_PAC)/lib/$(UAL_ARCH) \
	-L$(UAL_CORE)/lib/$(UAL_ARCH) \
	-lPac -lUal -lPacSMF -lTeapot -lPacOptics 

ifeq ($(USE_GPU), TRUE)
CUDA_INC  = -I/usr/local/cuda/include
LIBS += -L/usr/local/cuda/lib64 -lcudart
#LIBS += -L/usr/local/pgiCDK-11.5/linux86-64/2011/cuda/3.1/lib64 -lcudart
NVCC	= nvcc -arch=sm_20
NVCCFLAGS  = --compiler-options '-O -fpic -g'
endif

$(UAL_SPINK)/lib/$(UAL_ARCH)/obj/%.o : %.cc
	$(CC) $(CCFLAGS) $(INC) -c $< -o $@;

ifeq ($(USE_GPU), TRUE)
$(UAL_SPINK)/lib/$(UAL_ARCH)/obj/%.cu.o : %.cu
	$(NVCC) $(INC) -g --compiler-options '-fpic' -c  $< -o $@;
endif

