include $(UAL)/env/$(UAL_ARCH)/Makefile.config

INC      = -I$(UAL_TEAPOT)/src -I$(UAL_PAC)/src  -I$(UAL_CORE)/include -I$(UAL_ZLIB)/src
LIBS     = -L$(UAL_TEAPOT)/lib/$(UAL_ARCH) -L$(UAL_PAC)/lib/$(UAL_ARCH) \
	 	-L$(UAL_ZLIB)/lib/$(UAL_ARCH) \
		-L$(UAL_CORE)/lib/$(UAL_ARCH) -lUal -ldl 
LIBS += -L$(UAL)/tools/lib/$(UAL_ARCH)		-lgsl -lgslcblas

$(UAL_TEAPOT)/lib/$(UAL_ARCH)/obj/%.o : %.cc
	$(CC) $(CCFLAGS) $(INC) -c $< -o $@;

