include $(UAL)/env/$(UAL_ARCH)/Makefile.config

INC      = -I$(UAL_SXF)/src
INC     += -I$(UAL_PAC)/src 
INC     += -I$(UAL_ZLIB)/src 
INC     += -I$(UAL_CORE)/include 
INC     += -I$(SXF)/src

LIBS     = -L$(UAL_SXF)/lib/$(UAL_ARCH) 
LIBS    += -L$(UAL_PAC)/lib/$(UAL_ARCH) 	-lPacSMF -lPacOptics -lPac 
LIBS    += -L$(UAL_ZLIB)/lib/$(UAL_ARCH) 	-lZTps 
LIBS    += -L$(UAL_CORE)/lib/$(UAL_ARCH) 	-lUal  
LIBS    += -L$(SXF)/lib/$(SXF_ARCH) 		-lSXF


$(UAL_SXF)/lib/$(SXF_ARCH)/obj/%.o : %.cc
	$(CC) $(CCFLAGS) $(INC) -g -c $< -o $@;
