include $(UAL)/env/$(UAL_ARCH)/Makefile.config

INC      = -I$(UAL)/ext/ADXF/src
INC     += -I$(UAL_PAC)/src 
INC     += -I$(UAL_ZLIB)/src 
INC     += -I$(UAL)/codes/UAL/include 
INC     += -I$(UAL)/tools/include 

LIBS     = -L$(UAL)/ext/ADXF/lib/$(UAL_ARCH) 
LIBS    += -L$(UAL_PAC)/lib/$(UAL_ARCH) 	-lPacSMF -lPacOptics -lPac 
LIBS    += -L$(UAL_ZLIB)/lib/$(UAL_ARCH) 	-lZTps 
LIBS    += -L$(UAL_CORE)/lib/$(UAL_ARCH) 	-lUal 
LIBS    += -L$(UAL)/tools/lib/$(UAL_ARCH) 	-lxerces-c -lmuparser 


$(UAL)/ext/ADXF/lib/$(UAL_ARCH)/obj/%.o : %.cc
	$(CC) $(CCFLAGS) $(INC) -g -c $< -o $@;
