CORE = $(SXF)

MAKE = make
PERL = perl

RM     = rm
YACC   = bison # yacc
LEX    = flex
YFLAGS = -t -d
LFLAGS = -t -B 

GPERF    = gperf
CXX2HTML = $(CORE)/tools/cxx2html/bin/cxx2html.pl

CC       = g++                              # Compiler
CCFLAGS  = -O -fpic -ansi -pedantic -Wall   # Compilation flags
DLD      = g++                              # Dynamic linker
DLDFLAGS = -shared                          # Dynamic linker flags
LD       = g++                              # Linker
LDFLAGS  =                                  # Linker flags
SOEXT    = so

AR       = ar
ARFLAGS  = cr
RANLIB   = ranlib

INC      = -I$(CORE)/src
LIBS     = -L$(CORE)/lib/$(SXF_ARCH)

$(CORE)/lib/$(SXF_ARCH)/obj/%.o : %.cc
	$(CC) $(CCFLAGS) $(INC) $(LIBS) -c $< -o $@;

