include $(UAL)/env/$(UAL_ARCH)/Makefile.config

INC      = 	-I$(UAL_AIM)/src \
		-I$(UAL_PAC)/src \
		-I$(UAL_ZLIB)/src \
		-I$(UAL_CORE)/include \
		-I$(UAL)/tools/include

LIBS     =	-L$(UAL_AIM)/lib/$(UAL_ARCH) \
		-L$(UAL_PAC)/lib/$(UAL_ARCH) -lPac \
		-L$(UAL_CORE)/lib/$(UAL_ARCH) -lUal \
		-L$(UAL)/tools/lib/$(UAL_ARCH) -lrfftw -lfftw

$(UAL_AIM)/lib/$(UAL_ARCH)/obj/%.o : %.cc
	$(CC) $(CCFLAGS) $(INC) -c $< -o $@;
